name: Build .NET MAUI Installers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  windows-installer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Build .NET MAUI Windows Application Installer
        run: |
          dotnet publish Maui.PipelinesApp/Maui.PipelinesApp.csproj -f net8.0-windows10.0.19041.0 -c Release `
            -p:RuntimeIdentifierOverride=win10-x64 `
            -p:WindowsPackageType=None `
            -p:PublishSingleFile=true `
            -p:SelfContained=true

      - name: Build Installer using Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ./BMDRM.iss

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: '**/*.exe'

  macos-installer:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Build .NET MAUI macOS Application
        run: |
          dotnet publish Maui.PipelinesApp/Maui.PipelinesApp.csproj -f net8.0-maccatalyst -c Release \
            -p:CodesignKey="" \
            -p:CodesignProvision="" \
            -p:CreatePackage=false

      - name: Move .app to Output Directory
        run: |
          mkdir -p output
          APP_NAME="Maui.PipelinesApp.app"
          APP_PATH="Maui.PipelinesApp/bin/Release/net8.0-maccatalyst/$APP_NAME"
          mv "$APP_PATH" output/

      - name: Create macOS PKG Installer from .app
        run: |
          pkgbuild --root output/Maui.PipelinesApp.app \
                   --identifier com.bmdrm.maui \
                   --version 1.0.0 \
                   --install-location /Applications \
                   output/Maui.pkg

      - name: Upload macOS Installer
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: output/Maui.pkg
          
  release:
    needs: [windows-installer, macos-installer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: v${{ github.sha }}
          name: Release v${{ github.sha }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          artifacts: |
            artifacts/windows-installer/**
            artifacts/macos-installer/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
